// Parses CD_Club_Mixes_CLEAN_ONE_TAB.csv into mixes.js for the site.
// Run: node build-data.js
const fs = require('fs');
const path = require('path');

function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ',') { row.push(field); field = ''; }
      else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
      else if (c !== '\r') field += c;
    }
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const CURATOR_CANON = {
  'caleb': 'Caleb Mayo',
  'john (bonus!)': 'John Mayo',
  'david': 'David Satin',
  'david o. satin': 'David Satin',
  'stef': 'Stef Lynch',
  'stefanie lynch': 'Stef Lynch',
  'kimmy yaara gal': 'Kimmy Gal',
  'tiger': 'Tiger Smith',
  'jay': 'Jay Decator',
  'jay (bonus!)': 'Jay Decator',
  'colleenie beanie': 'Colleen Cassidy',
  'lisa': 'Lisa Keller',
  'rachel': 'Rachel Gariepy',
  'nina': 'Nina Beckhardt',
  'sloan': 'Andrew Sloan',
  'brian brown': 'Brian Brown',
};

function canonCurator(name) {
  const n = (name || '').trim();
  return CURATOR_CANON[n.toLowerCase()] || n;
}

function isUrl(s) { return /^https?:\/\//i.test((s || '').trim()); }
function clean(s) { return (s || '').replace(/\s+/g, ' ').trim(); }

// Era = cycle if present, else site section, else Uncatalogued
function deriveEra(cycle, section) {
  const c = clean(cycle), s = clean(section);
  if (c) return c.split('/')[0].trim();
  if (s === '2023') return '2023';
  if (s) return 'The Archives';
  return 'Uncatalogued';
}

const ERA_ORDER = ['2009', '2014', 'Summer 2018', 'Winter 2019', 'Summer 2020', 'Fall 2021', '2023', 'The Archives', 'Bonus', 'Uncatalogued'];

// Image fixes: CSV references pending/Slide*.JPG that don't exist, and misses
// a couple of covers that do exist in images/.
const IMAGE_OVERRIDES = {
  'Nighthawks Diner Jukebox': 'images/nighthawks.jpg',
  'Nothin Fancy': 'images/nothingfancy.png',
};

const csv = fs.readFileSync(path.join(__dirname, 'CD_Club_Mixes_CLEAN_ONE_TAB.csv'), 'utf8');
const rows = parseCSV(csv);
const header = rows.shift();

const SKIP_TITLES = new Set();
const mixes = [];
const seen = new Set();

for (const r of rows) {
  const [curator, title, spotify, apple, desc, vibe, cycle, onSite, siteTitle, section, image, notes] = r.map(x => x || '');
  const rawTitle = title.replace(/\s*\n\s*/g, ' / ').trim();
  if (!rawTitle) continue;
  // Orphan duplicate of Jeremy Dorfman's mix (no curator)
  if (rawTitle === 'Remembrance of Things Past: Low' && !clean(curator)) continue;
  // Duplicate of "Boy Groups and Girl Bands" (same Apple link)
  if (rawTitle === 'Boy & Girl Groups') continue;

  const displayTitle = clean(siteTitle) || rawTitle;
  const key = (canonCurator(curator) + '|' + displayTitle).toLowerCase();
  if (seen.has(key)) continue;
  seen.add(key);

  let img = clean(image);
  if (IMAGE_OVERRIDES[rawTitle]) img = IMAGE_OVERRIDES[rawTitle];
  if (img && !fs.existsSync(path.join(__dirname, img))) img = '';

  mixes.push({
    title: displayTitle,
    altTitle: displayTitle !== rawTitle ? rawTitle : '',
    curator: canonCurator(curator),
    spotify: isUrl(spotify) ? clean(spotify) : '',
    apple: isUrl(apple) ? clean(apple) : '',
    prompt: (desc || '').trim(),
    vibe: clean(vibe),
    era: deriveEra(cycle, section),
    image: img,
  });
}

// Upgrade Smarty Animals to the merged playlist link from v1 site data
const smarty = mixes.find(m => m.title === 'Smarty Animals');
if (smarty) {
  smarty.title = 'Smarty Animals / Smarty Animals XXL';
  smarty.spotify = 'https://open.spotify.com/playlist/7vLRoGdbRuGMe9XDL8aW2K';
}

// Entries that were on the v1 site but missing from the spreadsheet
mixes.push(
  {
    title: "We're All in This Together", altTitle: '', curator: 'John Mayo',
    spotify: 'https://open.spotify.com/playlist/6RyGLTqllGEGv9fnkz2IGO', apple: '',
    prompt: 'Songs about togetherness and love and community support.',
    vibe: 'Togetherness', era: 'Bonus', image: '',
  },
  {
    title: '70s Sitcoms', altTitle: '', curator: 'Nina Beckhardt',
    spotify: '', apple: '', prompt: '', vibe: '', era: '2023', image: '',
  },
  {
    title: 'Baby Baby Baby', altTitle: '', curator: 'Lisa Keller',
    spotify: '', apple: '', prompt: '', vibe: '', era: '2023', image: '',
  },
);

const eraKey = e => { const i = ERA_ORDER.indexOf(e); return i === -1 ? 99 : i; };
mixes.sort((a, b) => eraKey(a.era) - eraKey(b.era) || a.title.localeCompare(b.title));

const out = '// Generated by build-data.js — do not edit by hand.\nconst MIXES = ' +
  JSON.stringify(mixes, null, 1) + ';\nconst ERA_ORDER = ' + JSON.stringify(ERA_ORDER) + ';\n';
fs.writeFileSync(path.join(__dirname, 'mixes.js'), out, 'utf8');

const curators = new Set(mixes.map(m => m.curator).filter(Boolean));
console.log(`Wrote mixes.js: ${mixes.length} mixes, ${curators.size} curators, ${mixes.filter(m => m.image).length} with artwork`);
